In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import datetime

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/employer-data/Employers_data.csv

In [2]:
df = pd.read_csv('/kaggle/input/employer-data/Employers_data.csv')
df.shape

(10000, 10)

In [3]:
df.dtypes

Employee_ID          int64
Name                object
Age                  int64
Gender              object
Department          object
Job_Title           object
Experience_Years     int64
Education_Level     object
Location            object
Salary               int64
dtype: object

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       10000 non-null  int64
 1   Name              10000 non-null  object
 2   Age               10000 non-null  int64
 3   Gender            10000 non-null  object
 4   Department        10000 non-null  object
 5   Job_Title         10000 non-null  object
 6   Experience_Years  10000 non-null  int64
 7   Education_Level   10000 non-null  object
 8   Location          10000 non-null  object
 9   Salary            10000 non-null  int64
dtypes: int64(4), object(6)
memory usage: 781.4+ KB

In [5]:
df.describe()

       Employee_ID           Age  Experience_Years         Salary
count  10000.00000  10000.000000      10000.000000   10000.000000
mean    5000.50000     35.455900         12.370900  115381.500000
std     2886.89568     10.000213          9.148951   46066.139047
min        1.00000     21.000000          0.000000   25000.000000
25%     2500.75000     27.000000          5.000000   70000.000000
50%     5000.50000     34.000000         10.000000  120000.000000
75%     7500.25000     43.000000         19.000000  150000.000000
max    10000.00000     60.000000         37.000000  215000.000000

In [6]:
df.head()

,Employee_ID,Name,Age,Gender,Department,Job_Title,Experience_Years,Education_Level,Location,Salary
0,1,Merle Ingram,24,Female,Engineering,Engineer,1,Master,Austin,90000
1,2,John Mayes,56,Male,Sales,Executive,33,Master,Seattle,195000
2,3,Carlos Wille,21,Male,Engineering,Intern,1,Bachelor,New York,35000
3,4,Michael Bryant,30,Male,Finance,Analyst,9,Bachelor,New York,75000
4,5,Paula Douglas,25,Female,HR,Analyst,2,Master,Seattle,70000

In [7]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'Department', 'Job_Title',
       'Experience_Years', 'Education_Level', 'Location', 'Salary'],
      dtype='object')

In [8]:
# reorder the dataframe based on employee names
df.sort_values(by= "Name")

,Employee_ID,Name,Age,Gender,Department,Job_Title,Experience_Years,Education_Level,Location,Salary
3103,3104,Aaron Biderman,45,Male,Finance,Manager,22,Master,New York,140000
4984,4985,Aaron Chaney,39,Male,Marketing,Manager,16,Master,San Francisco,135000
4416,4417,Aaron Davis,49,Male,Finance,Executive,26,Master,New York,190000
103,104,Aaron Davis,38,Male,HR,Executive,15,Master,Chicago,165000
9203,9204,Aaron Defosses,42,Male,Finance,Executive,15,PhD,Chicago,175000
...,...,...,...,...,...,...,...,...,...,...
281,282,Zachary Bell,42,Male,Sales,Executive,19,Master,Chicago,170000
835,836,Zachary Lanser,42,Male,HR,Executive,19,Master,Seattle,175000
3460,3461,Zachary Mcbride,23,Male,Sales,Analyst,0,Master,San Francisco,70000
4672,4673,Zachary Reese,37,Male,Marketing,Manager,14,Master,Austin,130000
8309,8310,Zulma Burke,23,Female,Engineering,Engineer,0,Master,San Francisco,80000

In [9]:
# let's create 2 new columns: first and last name
df[['first_name', 'last_name']] = df['Name'].str.split(' ',expand=True)
df = df[['Employee_ID', 'Name', 'first_name', 'last_name', 'Age', 'Gender', 'Department', 'Job_Title',
       'Experience_Years', 'Education_Level', 'Location', 'Salary']]
df.head()

,Employee_ID,Name,first_name,last_name,Age,Gender,Department,Job_Title,Experience_Years,Education_Level,Location,Salary
0,1,Merle Ingram,Merle,Ingram,24,Female,Engineering,Engineer,1,Master,Austin,90000
1,2,John Mayes,John,Mayes,56,Male,Sales,Executive,33,Master,Seattle,195000
2,3,Carlos Wille,Carlos,Wille,21,Male,Engineering,Intern,1,Bachelor,New York,35000
3,4,Michael Bryant,Michael,Bryant,30,Male,Finance,Analyst,9,Bachelor,New York,75000
4,5,Paula Douglas,Paula,Douglas,25,Female,HR,Analyst,2,Master,Seattle,70000

In [10]:
# top 10 first names
top10_first_names = df.groupby('first_name')['Employee_ID'].count().sort_values(ascending=False).head(10)
top10_first_names

first_name
James      239
John       183
Robert     159
Mary       156
Michael    147
David      138
William    122
Richard    106
Joseph      89
Charles     78
Name: Employee_ID, dtype: int64

In [11]:
# top 10 last names
top10_last_names = df.groupby('last_name')['Employee_ID'].count().sort_values(ascending=False).head(10)
top10_last_names

last_name
Smith       119
Williams     83
Johnson      82
Brown        76
Jones        70
Davis        54
Miller       51
Harris       40
Wilson       34
Lee          33
Name: Employee_ID, dtype: int64

In [12]:
# birth year
df['birth_year'] = datetime.datetime.now().year - df['Age']
df.head()

,Employee_ID,Name,first_name,last_name,Age,Gender,Department,Job_Title,Experience_Years,Education_Level,Location,Salary,birth_year
0,1,Merle Ingram,Merle,Ingram,24,Female,Engineering,Engineer,1,Master,Austin,90000,2001
1,2,John Mayes,John,Mayes,56,Male,Sales,Executive,33,Master,Seattle,195000,1969
2,3,Carlos Wille,Carlos,Wille,21,Male,Engineering,Intern,1,Bachelor,New York,35000,2004
3,4,Michael Bryant,Michael,Bryant,30,Male,Finance,Analyst,9,Bachelor,New York,75000,1995
4,5,Paula Douglas,Paula,Douglas,25,Female,HR,Analyst,2,Master,Seattle,70000,2000

In [13]:
df.sort_values(by="Salary", ascending=False).head()

,Employee_ID,Name,first_name,last_name,Age,Gender,Department,Job_Title,Experience_Years,Education_Level,Location,Salary,birth_year
3949,3950,Willis Holmes,Willis,Holmes,59,Male,HR,Executive,36,Master,Chicago,215000,1966
2132,2133,Mark Newman,Mark,Newman,59,Male,Finance,Executive,36,Master,New York,215000,1966
9423,9424,Alexander Compton,Alexander,Compton,59,Male,HR,Executive,36,Master,New York,215000,1966
7633,7634,Brian Lewis,Brian,Lewis,59,Male,Sales,Executive,36,Master,Austin,210000,1966
7750,7751,Somer Mayer,Somer,Mayer,60,Female,Sales,Executive,37,Master,Austin,210000,1965

In [14]:
titles = df['Job_Title'].str.lower()
titles

0        engineer
1       executive
2          intern
3         analyst
4         analyst
          ...
9995    executive
9996    executive
9997    executive
9998      manager
9999      analyst
Name: Job_Title, Length: 10000, dtype: object

In [15]:
df[df['Job_Title'].str.lower().str.contains("exe")]

,Employee_ID,Name,first_name,last_name,Age,Gender,Department,Job_Title,Experience_Years,Education_Level,Location,Salary,birth_year
1,2,John Mayes,John,Mayes,56,Male,Sales,Executive,33,Master,Seattle,195000,1969
13,14,Alice Elvin,Alice,Elvin,40,Female,Sales,Executive,13,PhD,Chicago,175000,1985
14,15,Carolyn Bell,Carolyn,Bell,59,Female,HR,Executive,32,PhD,Chicago,205000,1966
16,17,Josefina Johnson,Josefina,Johnson,57,Female,Finance,Executive,30,PhD,Seattle,195000,1968
17,18,Mary Abraham,Mary,Abraham,44,Female,HR,Executive,21,Master,New York,175000,1981
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,Elaine Douglas,Elaine,Douglas,59,Female,HR,Executive,32,PhD,New York,200000,1966
9993,9994,Pedro Caul,Pedro,Caul,51,Male,Finance,Executive,28,Master,New York,200000,1974
9995,9996,Thomas Rossin,Thomas,Rossin,51,Male,Sales,Executive,28,Master,Austin,185000,1974
9996,9997,Christie King,Christie,King,36,Female,Sales,Executive,9,PhD,San Francisco,165000,1989
9997,9998,Alfred Keller,Alfred,Keller,57,Male,Sales,Executive,30,PhD,New York,200000,1968

Top 10 highest paid by first name, last name, Job Title, age, education level, Location, Age, and Experience Level
Percentage of male vs female in the top 10% and top 1% of highest paid employees

In [16]:
# top 10 highest paid
df.sort_values(by="Salary", ascending=False).head(10)

,Employee_ID,Name,first_name,last_name,Age,Gender,Department,Job_Title,Experience_Years,Education_Level,Location,Salary,birth_year
3949,3950,Willis Holmes,Willis,Holmes,59,Male,HR,Executive,36,Master,Chicago,215000,1966
2132,2133,Mark Newman,Mark,Newman,59,Male,Finance,Executive,36,Master,New York,215000,1966
9423,9424,Alexander Compton,Alexander,Compton,59,Male,HR,Executive,36,Master,New York,215000,1966
7633,7634,Brian Lewis,Brian,Lewis,59,Male,Sales,Executive,36,Master,Austin,210000,1966
7750,7751,Somer Mayer,Somer,Mayer,60,Female,Sales,Executive,37,Master,Austin,210000,1965
5416,5417,Linda Vigil,Linda,Vigil,60,Female,Sales,Executive,37,Master,San Francisco,210000,1965
3893,3894,Caroline Brown,Caroline,Brown,56,Female,Finance,Executive,33,Master,Austin,210000,1969
369,370,Shaun Bernhardt,Shaun,Bernhardt,59,Male,Sales,Executive,36,Master,Austin,210000,1966
8432,8433,Michael Crosby,Michael,Crosby,60,Male,Finance,Executive,33,PhD,New York,210000,1965
2730,2731,Scott Karam,Scott,Karam,58,Male,Sales,Executive,35,Master,New York,210000,1967

 Average pay by age, gender, title, experience, education, and salary

In [17]:
# function for average salary
def average_salary_by(category):
    avg_salary = df.groupby(category)['Salary'].mean().sort_values(ascending=False)
    return avg_salary

def max_salary_by(category):
    max_salary = df.groupby(category)['Salary'].max().sort_values(ascending=False)
    return max_salary

def min_salary_by(category):
    min_salary = df.groupby(category)['Salary'].min().sort_values(ascending=False)
    return min_salary

def total_salary_by(category):
    total_salary= df.groupby(category)['Salary'].sum().sort_values(ascending=False)
    return total_salary

In [18]:
average_salary_by("Age")

Age
60    204492.753623
59    204097.222222
58    201902.173913
57    199375.000000
56    198787.878788
55    195882.352941
54    194772.727273
53    194097.222222
52    190625.000000
51    189365.079365
50    164279.475983
49    161778.656126
48    160465.587045
47    158307.392996
46    157216.981132
45    156497.797357
44    153711.111111
43    150601.659751
42    147899.159664
41    146615.044248
40    139197.324415
38    136809.523810
39    135346.534653
37    132996.688742
36    132184.300341
35    128350.168350
34    116659.574468
33    116065.573770
32    114050.632911
31    111570.247934
30     89581.818182
29     79571.428571
28     77772.020725
27     74987.468672
26     72259.358289
25     62700.381679
24     62595.978062
23     60414.201183
22     53695.652174
21     35689.655172
Name: Salary, dtype: float64

In [19]:
max_salary_by("Age")

Age
59    215000
60    210000
58    210000
56    210000
54    205000
51    205000
53    205000
52    205000
55    205000
57    205000
49    200000
50    195000
48    195000
47    190000
46    190000
45    190000
44    185000
43    185000
42    180000
41    180000
40    180000
38    180000
39    175000
37    175000
36    175000
35    170000
34    135000
31    130000
32    130000
33    130000
30    125000
29    105000
28    105000
23    100000
27    100000
26    100000
24    100000
25     95000
22     70000
21     45000
Name: Salary, dtype: int64

In [20]:
min_salary_by("Age")

Age
60    200000
59    195000
58    195000
57    190000
56    190000
55    185000
54    185000
53    185000
51    180000
52    180000
50    140000
49    140000
48    135000
47    135000
46    135000
45    130000
44    130000
43    130000
42    125000
41    125000
39    105000
40    105000
36    100000
33     95000
38     95000
37     95000
35     95000
34     95000
32     90000
31     90000
30     65000
29     65000
28     65000
27     55000
26     55000
24     25000
23     25000
22     25000
25     25000
21     25000
Name: Salary, dtype: int64

In [21]:
total_salary_by("Age")

Age
30    49270000
38    43095000
40    41620000
39    41010000
49    40930000
47    40685000
37    40165000
48    39635000
36    38730000
35    38120000
50    37620000
43    36295000
45    35525000
42    35200000
44    34585000
24    34240000
46    33330000
41    33135000
25    32855000
29    30635000
23    30630000
28    30020000
27    29920000
33    28320000
34    27415000
32    27030000
26    27025000
31    27000000
58    18575000
22    18525000
55    16650000
57    15950000
52    15250000
59    14695000
60    14110000
53    13975000
56    13120000
54    12855000
51    11930000
21     4140000
Name: Salary, dtype: int64

Create pivot table like data frame with each categories and add metrics:
- Number of employees
- Break down of employees by gender
- avg, min, max age
- avg, min, max years of experience
- avg, min, max salary

In [22]:
# create bins

In [23]:
def generate_bins_for(column, bin_edge_min, bin_edge_max, bin_interval):
    """
        takes in a numerical column and creates bins based on specified parameters.
        
        parameters:

            column = the dataframe column to be binned. Must be a numerical column
            bin_edge_min = starting bin edge value
            bin_edge_max = ending bin edge value. Must be greater than the bin edge min by at least 1 interval
            bin_interval = determines the exact bin edges between the bin_edge_min and bin_edge_max

        returns:
            a array like object representing the bin for each value -> pd.cut 
    """

    if df[column].dtype != int:
        print("Column Type Error. Must provide a numerical column")
    else:
        if bin_edge_max >= bin_edge_min + bin_interval:
            bin_array = np.arange(bin_edge_min, bin_edge_max, bin_interval)
            binned_data = pd.cut(df[column], bins = bin_array, precision=0, right=False)
            return binned_data
        else:
            print("bin_edge_max must be greater than bin_edge_min by at least 1 interval")

In [24]:
df['age_group'] = generate_bins_for("Age",20,65,5)
df['salary_group'] = generate_bins_for("Salary", 0, 250000, 25000)

In [25]:
df.head()

,Employee_ID,Name,first_name,last_name,Age,Gender,Department,Job_Title,Experience_Years,Education_Level,Location,Salary,birth_year,age_group,salary_group
0,1,Merle Ingram,Merle,Ingram,24,Female,Engineering,Engineer,1,Master,Austin,90000,2001,"[20, 25)","[75000, 100000)"
1,2,John Mayes,John,Mayes,56,Male,Sales,Executive,33,Master,Seattle,195000,1969,"[55, 60)","[175000, 200000)"
2,3,Carlos Wille,Carlos,Wille,21,Male,Engineering,Intern,1,Bachelor,New York,35000,2004,"[20, 25)","[25000, 50000)"
3,4,Michael Bryant,Michael,Bryant,30,Male,Finance,Analyst,9,Bachelor,New York,75000,1995,"[30, 35)","[75000, 100000)"
4,5,Paula Douglas,Paula,Douglas,25,Female,HR,Analyst,2,Master,Seattle,70000,2000,"[25, 30)","[50000, 75000)"

Start with getting the upper bound.

To get the upper bound, you have to take the lower bound, increment it by an interval until the upper bound is greater or equal to the max value.

In [26]:
# def get_lower_bound(column):
#     """
#         get the lower bound of a numerical series.
#         returns an even number.
#     """
#     if df[column].dtype == int:
#         if df[column].min() % 2 != 0:
#             lower_bound = df[column].min() - 1
#             print(lower_bound)
#     else: print("Column type error. Must be of type int.")

In [27]:
# highest paid employees for each first name in the dataset set
# for example, who is the highest paid for all employee names that start with A?
# df_first_names = df[['first_name','Salary']].sort_values(by="first_name").reset_index(drop=True)
# df_first_names.shape

In [28]:
# df_first_names

In [29]:
# df_first_names.groupby(["first_name"])["Salary"].nlargest(1)

In [30]:
# highest paid person with the name that starts with A
# names_starts_with_a = df_first_names.loc[df_first_names['first_name'].str.startswith('A')]
# names_starts_with_a.sort_values(by="Salary",ascending=False)

In [31]:
# names_starts_with_a.groupby("first_name").apply(lambda x: x.sort_values("Salary", ascending=False)).reset_index(drop=True)

In [32]:
# # names_starts_with_a['first_name_starts_with'] = 
# names_starts_with_a['first_name'].apply(lambda x: pd.Series(list(x)))

In [33]:
# first_name_dict = dict(names_starts_with_a['first_name'].str.split(pat="\s*"))
# first_name_dict